In [1]:
import psycopg2
import psycopg2.extras
from optparse import OptionParser, OptionGroup
import sys

In [2]:
# Connect to an existing database
conn1 = psycopg2.connect("dbname=DB-project user=postgres password=admin")
conn2 = psycopg2.connect("dbname=Data-Warehouse user=postgres password=admin")

In [3]:
cur1 = conn1.cursor()
cur2 = conn2.cursor()

conn1.autocommit = True
conn2.autocommit = True

# Pipeline

In [4]:
def columns(cursor, table):
    cursor.execute("""
    SELECT COLUMN_NAME
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = '{table}'
    ORDER BY ORDINAL_POSITION
    """.format(table=table))
    
def attributes(table):
    with conn2.cursor() as cursor2:
        columns(cursor2, table)
        cols = cursor2.fetchall()
        attributes = []
        for col in cols:
            attributes.append(col[0])
        return attributes

In [5]:
def trigger(table):
    atts = attributes(table)
    s = ''
    s_old = ''
    for att in atts:
        s += att + ', '
    for att in atts:
        s_old += 'OLD.' + att + ', '
    query = """CREATE FUNCTION {table}_history() RETURNS trigger AS ${table}_history$
    BEGIN
        IF (TG_OP = 'UPDATE') THEN
            INSERT INTO {table}_old(""".format(table=table)
    query += s
    query += """change_date, change)
            VALUES("""
    query += s_old
    query += """CURRENT_DATE, 'update');
        ELSEIF (TG_OP = 'DELETE') THEN
            INSERT INTO {table}_old(""".format(table=table)
    query += s
    query += """change_date, change)
            VALUES("""
    query += s_old
    query += """CURRENT_DATE, 'delete');
        END IF;
        RETURN NULL; -- result is ignored since this is an AFTER trigger
    END;
    ${table}_history$ LANGUAGE plpgsql;

    CREATE TRIGGER {table}_history AFTER UPDATE OR DELETE ON {table}
    FOR EACH ROW EXECUTE FUNCTION {table}_history();
    """.format(table=table)
    
    return query

In [6]:
print(trigger('person'))

CREATE FUNCTION person_history() RETURNS trigger AS $person_history$
    BEGIN
        IF (TG_OP = 'UPDATE') THEN
            INSERT INTO person_old(person_id, last_name, first_name, insert_date, change_date, change)
            VALUES(OLD.person_id, OLD.last_name, OLD.first_name, OLD.insert_date, CURRENT_DATE, 'update');
        ELSEIF (TG_OP = 'DELETE') THEN
            INSERT INTO person_old(person_id, last_name, first_name, insert_date, change_date, change)
            VALUES(OLD.person_id, OLD.last_name, OLD.first_name, OLD.insert_date, CURRENT_DATE, 'delete');
        END IF;
        RETURN NULL; -- result is ignored since this is an AFTER trigger
    END;
    $person_history$ LANGUAGE plpgsql;

    CREATE TRIGGER person_history AFTER UPDATE OR DELETE ON person
    FOR EACH ROW EXECUTE FUNCTION person_history();

In [7]:
def tables(cursor):
    cursor.execute("SELECT tablename FROM pg_tables WHERE schemaname='public'")
    tables = []
    for row in cursor.fetchall():
        tables.append(row[0])
    return tables

with conn1.cursor() as cursor1:
    tables = tables(cursor1)
    print('list of tables:\n', tables)
    for table in tables:
        print('\n\n', trigger(table), '\n\n')

list of tables:
 ['person', 'book', 'languageb', 'genre', 'user_library', 'written_by', 'translated_by', 'language_book', 'genre_book', 'borrowed']


 CREATE FUNCTION person_history() RETURNS trigger AS $person_history$
    BEGIN
        IF (TG_OP = 'UPDATE') THEN
            INSERT INTO person_old(person_id, last_name, first_name, insert_date, change_date, change)
            VALUES(OLD.person_id, OLD.last_name, OLD.first_name, OLD.insert_date, CURRENT_DATE, 'update');
        ELSEIF (TG_OP = 'DELETE') THEN
            INSERT INTO person_old(person_id, last_name, first_name, insert_date, change_date, change)
            VALUES(OLD.person_id, OLD.last_name, OLD.first_name, OLD.insert_date, CURRENT_DATE, 'delete');
        END IF;
        RETURN NULL; -- result is ignored since this is an AFTER trigger
    END;
    $person_history$ LANGUAGE plpgsql;

    CREATE TRIGGER person_history AFTER UPDATE OR DELETE ON person
    FOR EACH ROW EXECUTE FUNCTION person_history();





 CREATE FUNCTION book_history() RETURNS trigger AS $book_history$
    BEGIN
        IF (TG_OP = 'UPDATE') THEN
            INSERT INTO book_old(isbn, number_available, title, description, edition, published_date, publisher, main_author, main_language, main_genre, insert_date, change_date, change)
            VALUES(OLD.isbn, OLD.number_available, OLD.title, OLD.description, OLD.edition, OLD.published_date, OLD.publisher, OLD.main_author, OLD.main_language, OLD.main_genre, OLD.insert_date, CURRENT_DATE, 'update');
        ELSEIF (TG_OP = 'DELETE') THEN
            INSERT INTO book_old(isbn, number_available, title, description, edition, published_date, publisher, main_author, main_language, main_genre, insert_date, change_date, change)
            VALUES(OLD.isbn, OLD.number_available, OLD.title, OLD.description, OLD.edition, OLD.published_date, OLD.publisher, OLD.main_author, OLD.main_language, OLD.main_genre, OLD.insert_date, CURRENT_DATE, 'delete');
        END IF;
        RETURN NULL; -- result is ignored since this is an AFTER trigger
    END;
    $book_history$ LANGUAGE plpgsql;

    CREATE TRIGGER book_history AFTER UPDATE OR DELETE ON book
    FOR EACH ROW EXECUTE FUNCTION book_history();





 CREATE FUNCTION languageb_history() RETURNS trigger AS $languageb_history$
    BEGIN
        IF (TG_OP = 'UPDATE') THEN
            INSERT INTO languageb_old(languageb, insert_date, change_date, change)
            VALUES(OLD.languageb, OLD.insert_date, CURRENT_DATE, 'update');
        ELSEIF (TG_OP = 'DELETE') THEN
            INSERT INTO languageb_old(languageb, insert_date, change_date, change)
            VALUES(OLD.languageb, OLD.insert_date, CURRENT_DATE, 'delete');
        END IF;
        RETURN NULL; -- result is ignored since this is an AFTER trigger
    END;
    $languageb_history$ LANGUAGE plpgsql;

    CREATE TRIGGER languageb_history AFTER UPDATE OR DELETE ON languageb
    FOR EACH ROW EXECUTE FUNCTION languageb_history();





 CREATE FUNCTION genre_history() RETURNS trigger AS $genre_history$
    BEGIN
        IF (TG_OP = 'UPDATE') THEN
            INSERT INTO genre_old(genre, insert_date, change_date, change)
            VALUES(OLD.genre, OLD.insert_date, CURRENT_DATE, 'update');
        ELSEIF (TG_OP = 'DELETE') THEN
            INSERT INTO genre_old(genre, insert_date, change_date, change)
            VALUES(OLD.genre, OLD.insert_date, CURRENT_DATE, 'delete');
        END IF;
        RETURN NULL; -- result is ignored since this is an AFTER trigger
    END;
    $genre_history$ LANGUAGE plpgsql;

    CREATE TRIGGER genre_history AFTER UPDATE OR DELETE ON genre
    FOR EACH ROW EXECUTE FUNCTION genre_history();





 CREATE FUNCTION user_library_history() RETURNS trigger AS $user_library_history$
    BEGIN
        IF (TG_OP = 'UPDATE') THEN
            INSERT INTO user_library_old(user_id, person_id, birth_date, register_date, register_number, telephone, address, insert_date, change_date, change)
            VALUES(OLD.user_id, OLD.person_id, OLD.birth_date, OLD.register_date, OLD.register_number, OLD.telephone, OLD.address, OLD.insert_date, CURRENT_DATE, 'update');
        ELSEIF (TG_OP = 'DELETE') THEN
            INSERT INTO user_library_old(user_id, person_id, birth_date, register_date, register_number, telephone, address, insert_date, change_date, change)
            VALUES(OLD.user_id, OLD.person_id, OLD.birth_date, OLD.register_date, OLD.register_number, OLD.telephone, OLD.address, OLD.insert_date, CURRENT_DATE, 'delete');
        END IF;
        RETURN NULL; -- result is ignored since this is an AFTER trigger
    END;
    $user_library_history$ LANGUAGE plpgsql;

    CREATE TRIGGER user_library_history AFTER UPDATE OR DELETE ON user_library
    FOR EACH ROW EXECUTE FUNCTION user_library_history();





 CREATE FUNCTION written_by_history() RETURNS trigger AS $written_by_history$
    BEGIN
        IF (TG_OP = 'UPDATE') THEN
            INSERT INTO written_by_old(written_id, person_id, book_id, insert_date, change_date, change)
            VALUES(OLD.written_id, OLD.person_id, OLD.book_id, OLD.insert_date, CURRENT_DATE, 'update');
        ELSEIF (TG_OP = 'DELETE') THEN
            INSERT INTO written_by_old(written_id, person_id, book_id, insert_date, change_date, change)
            VALUES(OLD.written_id, OLD.person_id, OLD.book_id, OLD.insert_date, CURRENT_DATE, 'delete');
        END IF;
        RETURN NULL; -- result is ignored since this is an AFTER trigger
    END;
    $written_by_history$ LANGUAGE plpgsql;

    CREATE TRIGGER written_by_history AFTER UPDATE OR DELETE ON written_by
    FOR EACH ROW EXECUTE FUNCTION written_by_history();





 CREATE FUNCTION translated_by_history() RETURNS trigger AS $translated_by_history$
    BEGIN
        IF (TG_OP = 'UPDATE') THEN
            INSERT INTO translated_by_old(translated_id, person_id, book_id, insert_date, change_date, change)
            VALUES(OLD.translated_id, OLD.person_id, OLD.book_id, OLD.insert_date, CURRENT_DATE, 'update');
        ELSEIF (TG_OP = 'DELETE') THEN
            INSERT INTO translated_by_old(translated_id, person_id, book_id, insert_date, change_date, change)
            VALUES(OLD.translated_id, OLD.person_id, OLD.book_id, OLD.insert_date, CURRENT_DATE, 'delete');
        END IF;
        RETURN NULL; -- result is ignored since this is an AFTER trigger
    END;
    $translated_by_history$ LANGUAGE plpgsql;

    CREATE TRIGGER translated_by_history AFTER UPDATE OR DELETE ON translated_by
    FOR EACH ROW EXECUTE FUNCTION translated_by_history();





 CREATE FUNCTION language_book_history() RETURNS trigger AS $language_book_history$
    BEGIN
        IF (TG_OP = 'UPDATE') THEN
            INSERT INTO language_book_old(lb_id, languageb, book_id, insert_date, change_date, change)
            VALUES(OLD.lb_id, OLD.languageb, OLD.book_id, OLD.insert_date, CURRENT_DATE, 'update');
        ELSEIF (TG_OP = 'DELETE') THEN
            INSERT INTO language_book_old(lb_id, languageb, book_id, insert_date, change_date, change)
            VALUES(OLD.lb_id, OLD.languageb, OLD.book_id, OLD.insert_date, CURRENT_DATE, 'delete');
        END IF;
        RETURN NULL; -- result is ignored since this is an AFTER trigger
    END;
    $language_book_history$ LANGUAGE plpgsql;

    CREATE TRIGGER language_book_history AFTER UPDATE OR DELETE ON language_book
    FOR EACH ROW EXECUTE FUNCTION language_book_history();





 CREATE FUNCTION genre_book_history() RETURNS trigger AS $genre_book_history$
    BEGIN
        IF (TG_OP = 'UPDATE') THEN
            INSERT INTO genre_book_old(gb_id, genre, book_id, insert_date, change_date, change)
            VALUES(OLD.gb_id, OLD.genre, OLD.book_id, OLD.insert_date, CURRENT_DATE, 'update');
        ELSEIF (TG_OP = 'DELETE') THEN
            INSERT INTO genre_book_old(gb_id, genre, book_id, insert_date, change_date, change)
            VALUES(OLD.gb_id, OLD.genre, OLD.book_id, OLD.insert_date, CURRENT_DATE, 'delete');
        END IF;
        RETURN NULL; -- result is ignored since this is an AFTER trigger
    END;
    $genre_book_history$ LANGUAGE plpgsql;

    CREATE TRIGGER genre_book_history AFTER UPDATE OR DELETE ON genre_book
    FOR EACH ROW EXECUTE FUNCTION genre_book_history();





 CREATE FUNCTION borrowed_history() RETURNS trigger AS $borrowed_history$
    BEGIN
        IF (TG_OP = 'UPDATE') THEN
            INSERT INTO borrowed_old(borrowed_id, user_id, book_id, deadline, number_books, borrowed_date, returned_date, insert_date, change_date, change)
            VALUES(OLD.borrowed_id, OLD.user_id, OLD.book_id, OLD.deadline, OLD.number_books, OLD.borrowed_date, OLD.returned_date, OLD.insert_date, CURRENT_DATE, 'update');
        ELSEIF (TG_OP = 'DELETE') THEN
            INSERT INTO borrowed_old(borrowed_id, user_id, book_id, deadline, number_books, borrowed_date, returned_date, insert_date, change_date, change)
            VALUES(OLD.borrowed_id, OLD.user_id, OLD.book_id, OLD.deadline, OLD.number_books, OLD.borrowed_date, OLD.returned_date, OLD.insert_date, CURRENT_DATE, 'delete');
        END IF;
        RETURN NULL; -- result is ignored since this is an AFTER trigger
    END;
    $borrowed_history$ LANGUAGE plpgsql;

    CREATE TRIGGER borrowed_history AFTER UPDATE OR DELETE ON borrowed
    FOR EACH ROW EXECUTE FUNCTION borrowed_history();